/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: edee810f949287fece4fa61b6f8e2557)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "EdgeButler";
	}
	interface Env {
		AI: Ai;
		EdgeButler: DurableObjectNamespace<import("./src/server").EdgeButler>;
	}
}
interface Env extends Cloudflare.Env {}
